"""Add device_type to Device model

Revision ID: 7db46d3936b6
Revises: e2d9d033ceda
Create Date: 2025-04-21 19:58:32.437830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db46d3936b6'
down_revision = 'e2d9d033ceda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###
