"""Add known_devices_snapshot to LoginSession

Revision ID: 904ab7e9a70c
Revises: 4dec4af8187e
Create Date: 2025-04-23 16:30:59.657673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text # 导入 text 用于执行原生 SQL


# revision identifiers, used by Alembic.
revision = '904ab7e9a70c'
down_revision = '4dec4af8187e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjust manually for batch mode ###
    with op.batch_alter_table('login_session', schema=None) as batch_op:
        # 在修改约束前，先更新现有的 NULL 值
        # 使用 SQLite 的 CURRENT_TIMESTAMP 作为默认值
        # 注意：确保这个默认值符合你的业务逻辑
        batch_op.execute(
            text("UPDATE login_session SET expiration_timestamp = CURRENT_TIMESTAMP WHERE expiration_timestamp IS NULL")
        )

        # 现在可以安全地修改列为 NOT NULL
        batch_op.alter_column('expiration_timestamp',
                   existing_type=sa.DATETIME(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjust manually for batch mode ###
    with op.batch_alter_table('login_session', schema=None) as batch_op:
        # 恢复为允许 NULL
        batch_op.alter_column('expiration_timestamp',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        # 注意：downgrade 通常不需要处理数据，因为允许 NULL 不会引起冲突
    # ### end Alembic commands ###
