"""remove  LoginSession.status

Revision ID: bf524feae85c
Revises: c4ad67caa0d2
Create Date: 2025-04-26 19:03:08.059649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf524feae85c'
down_revision = 'c4ad67caa0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_session', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True))

    # ### end Alembic commands ###
