"""Remove device_id column from Device table

Revision ID: d085f33ad789
Revises: b0b86145e0d8
Create Date: 2025-04-22 14:35:46.612035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd085f33ad789'
down_revision = 'b0b86145e0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - use batch mode for SQLite ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('device_name',
                   existing_type=sa.VARCHAR(length=64),
                   type_=sa.String(length=100),
                   existing_nullable=True)
        batch_op.alter_column('device_ip',
                   existing_type=sa.VARCHAR(length=64),
                   type_=sa.String(length=50),
                   existing_nullable=True)
        batch_op.alter_column('device_type',
                   existing_type=sa.VARCHAR(length=32),
                   type_=sa.String(length=50),
                   existing_nullable=True)
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - use batch mode for SQLite ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('device_type',
                   existing_type=sa.String(length=50),
                   type_=sa.VARCHAR(length=32),
                   existing_nullable=True)
        batch_op.alter_column('device_ip',
                   existing_type=sa.String(length=50),
                   type_=sa.VARCHAR(length=64),
                   existing_nullable=True)
        batch_op.alter_column('device_name',
                   existing_type=sa.String(length=100),
                   type_=sa.VARCHAR(length=64),
                   existing_nullable=True)

    # ### end Alembic commands ###
